// https://demo.templatemonster.com/demo/66344.html?_gl=1*g8ngwd*_ga*MjEwNzEzNjQ1Ni4xNjc4Mjg2ODg4*_ga_FTPYEGT5LY*MTcwOTcxOTMzMy4xNC4xLjE3MDk3MTk5OTMuOS4wLjA.

import Header from "@/component/mudole/header/header";
import "./globals.css";
import Footer from "@/component/mudole/footer/footer";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
}
